CREATE TABLE Sections (
	ID INT NOT NULL
		CONSTRAINT PK_Sections PRIMARY KEY CLUSTERED,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE Dishes (
	ID INT NOT NULL
		CONSTRAINT PK_Dishes PRIMARY KEY CLUSTERED,
	Name VARCHAR(50) NOT NULL,
	SectionID INT NOT NULL
		CONSTRAINT FK_Dishes_Sections FOREIGN KEY REFERENCES Sections(ID),
	Weight INT
);

CREATE TABLE Tags (
	ID INT NOT NULL
		CONSTRAINT PK_Tags PRIMARY KEY CLUSTERED,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE DishesTags (
	ID INT NOT NULL
		CONSTRAINT PK_DishesTags PRIMARY KEY CLUSTERED,
	DishID INT NOT NULL
		CONSTRAINT FK_DishesTags_Dishes FOREIGN KEY REFERENCES Dishes(ID),
	TagID INT NOT NULL
		CONSTRAINT FK_DishesTags_Tags FOREIGN KEY REFERENCES Tags(ID)
);

CREATE TABLE Ingredients (
	ID INT NOT NULL
		CONSTRAINT PK_Ingredients PRIMARY KEY CLUSTERED,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE DishesIngredients (
	ID INT NOT NULL
		CONSTRAINT PK_DishesIngredients PRIMARY KEY CLUSTERED,
	DishID INT NOT NULL
		CONSTRAINT FK_DishesIngredients_Dishes FOREIGN KEY REFERENCES Dishes(ID),
	IngredientID INT NOT NULL
		CONSTRAINT FK_DishesIngredients_Ingredients FOREIGN KEY REFERENCES Ingredients(ID),
	Weight INT
);

CREATE TABLE Prices (
	ID INT NOT NULL
		CONSTRAINT PK_Prices PRIMARY KEY CLUSTERED,
	DishID INT NOT NULL
		CONSTRAINT FK_Prices_Dishes FOREIGN KEY REFERENCES Dishes(ID),
	DateFrom DATE NULL,
	DateTo DATE NULL,
	Price MONEY
);
