CREATE TABLE Genders (
  Id INT PRIMARY KEY,
  Name NVARCHAR(50) NOT NULL
);

CREATE TABLE MaritalStatuses (
  Id INT PRIMARY KEY,
  Name NVARCHAR(50) NOT NULL
);

CREATE TABLE Grades (
  Id INT PRIMARY KEY,
  Name VARCHAR(2) NOT NULL,
  Description NVARCHAR(255) NULL
);

CREATE TABLE Faculties (
  Id INT PRIMARY KEY,
  Name NVARCHAR(500) NOT NULL
);
